spring:
  thymeleaf:
    mode: HTML

  profiles:
    active: dev
  messages:
    basename: i18n/messages

  mail:
    host: smtp.qq.com
    username: 1611606790@qq.com
    password:
    default-encoding: utf-8
    port: 465
    protocol: smtps
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true # 使用
          starttls: # 使用 SSL 安全协议，须如下配置
            enable: true
            required: true

Comment.avatar: /images/noface.jpg