spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: "061000"

  #设置thymeleaf模板引擎缓存，默认开启
  thymeleaf:
    cache: false
    prefix:
      classpath: /templates

mybatis:
  mapper-locations: classpath:dao/*.xml
  type-aliases-package: com.beifeng.dao

server:
  port: 8081

logging:
  level:
    root: info
    com.beifeng: debug
  file:
    name: spring.log



pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
